### ISSUE TITLE
Create simple-jupyter course repository

### ISSUE THREAD

**Issue by dadamsncsa** [nanoMFG/community#33]
## Description
Use our course template repo to create a skeleton course called "nanohub-simple-jupyter-tool".

## Details
- [ ] Create course repo in the nanoMFG org, public should be okay.
- [ ] Use the "nanoMFG/toolstart-jupyter" repo as the template repo.  Note the template here is NOT the template use to create a blank course ,rather the "template-repo" for the course--the one the use will get a copy of.  Confusing?
- [ ] Add to the nanoMFG learning lab dashboard as a course using: https://lab.github.com/nanoMFG/admin

**Comment by vickyli99** [comment]
I just created the repository, using the toolstart-jupyter template. and I tried to add to the nanoMFG learning lab dashboard, but the link is not working ?! Also, could you please help me delete a repository called simple-jupyter-notebook, I don't think I can delete a repository as a member of this organization, so I just archived it. It is a repository I created by mistake. Thanks!
