### ISSUE TITLE
Create a template for nanoMFG leaning lab courses

### ISSUE THREAD

**Issue by dadamsncsa** [nanoMFG/community#36]
## Description
Create basic template to use when spinning up a new course

## Details
- [x] Include basic elements needed
  - `config.yml`
    - Include commented out steps, say 1-10
  - `course-details.md`
  - `Readme.md`
  -  `responses/` directory with one or more canned responses.
  -  `LICENSE` - Use MIT with "University of Illinois" copyright 
- [x] Update repo setting to make it a template
- [x] Test and validate `config.yml`.

**Comment by briancy02** [comment]
Template is complete. Linking issues to steps work now!
