### ISSUE TITLE
Update Intro to nanoMFG Tool Development path

### ISSUE THREAD

**Issue by dadamsncsa** [nanoMFG/community#37]
### ToDo
* Remove the last 2 Github actions courses (CI and github script), I think these could go in the intermediate (or even advanced) track, but probably keep the hello world course.
* Plan to include the simple jupyter as the last course when we have it

**Comment by adamurish** [comment]
I think [Community Starter Kit](https://lab.github.com/githubtraining/community-starter-kit), [Uploading your project to GitHub](https://lab.github.com/githubtraining/uploading-your-project-to-github), and [Reviewing pull requests](https://lab.github.com/githubtraining/reviewing-pull-requests) should definitely be included, as these contain the essential information for getting a tool onto Github and available to the community. [Managing merge conflicts](https://lab.github.com/githubtraining/managing-merge-conflicts) might also be a good one to include, although it could fit better in another learning path.

**Comment by adamurish** [comment]
Opened [this pull request](https://github.com/nanoMFG/tool-dev-getting-started/pull/1) with initial courses

**Comment by dadamsncsa** [comment]
I merged the PR, I like the list you have, but I might suggest some changes.   I think we should keep the Intro track that you created, but change it a bit and create some a "intermediate" track.  I'm going to edit this issue for modifying the intro track and put it back in the backlog. Then create another on for the intermediate track.
