### ISSUE TITLE
create skeleton repo for python-best-practices

### ISSUE THREAD

**Issue by dadamsncsa** [nanoMFG/community#38]
- [x] Create course repo in the nanoMFG org, public should be okay.
- [x] Create course template. 
- [x] Add to the nanoMFG learning lab dashboard as a course using: https://lab.github.com/nanoMFG/admin

**Comment by briancy02** [comment]
@dadamsncsa 
Please review this issue and see if it can be closed. Check the [course](https://lab.github.com/nanoMFG/python-best-practices/4.0.0) I added and try it out. If you think it has all the elements you wanted for this issue, you can close this issue and if not you could add more tasks and I will work on them.
